version: 2.1

# Optional: use the Gradle ORB to leverage dependencies cache
orbs:
  gradle: circleci/gradle@2.1.0

executors:
  openjdk-8-executor:
    docker:
      - image: 'circleci/openjdk:8'

jobs:
  # Name the job "run-oss-index-audit"
  run-oss-index-audit:
    executor: openjdk-8-executor
    steps:
      - checkout # check out source code to working directory
      - restore_cache: # Optional: cache the OSS Index data on a custom folder to avoid depending on OS-specific filesystems
          key: ossindex-gradle-cache
      - gradle/with_cache: # From the Gradle ORB, restore dependencies and wrapper from CircleCI cache before running the steps and saves them on success
          steps:
            - run:
                name: ossIndexAudit
                command: ./gradlew ossIndexAudit --no-daemon
      - save_cache: # Optional: cache the OSS Index data on a custom folder to avoid depending on OS-specific filesystems
          paths:
            - ~/.ossIndexCache # Check the file "build.gradle" to see how to set the cache directory on the plugin
          key: ossindex-gradle-cache

workflows:
  # Name the workflow "oss-index-audit"
  oss-index-audit:
    jobs:
      - run-oss-index-audit
