version: 2.1

# Optional: use the Gradle ORB to leverage dependencies cache
orbs:
  gradle: circleci/gradle@2.1.0

executors:
  openjdk-8-executor:
    docker:
      - image: 'circleci/openjdk:8'

jobs:
  run-oss-index-audit:
    executor: openjdk-8-executor
    steps:
      - checkout # check out source code to working directory
      - gradle/with_cache:
          steps:
            - run:
                name: ossIndexAudit
                command: ./gradlew --no-daemon ossIndexAudit --info

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "oss-index-audit"
  oss-index-audit:
    # Run the ossIndexAudit job in its own container
    jobs:
      - run-oss-index-audit
