name: Run Gradle on PRs

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: run ossIndexAudit
      run: |
        ./gradlew ossIndexAudit --no-daemon --info
