name: Run ossIndexAudit using Gradle with cache

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/cache@v1 # This action only saves cache for successful jobs
      name: Gradle cache
      with:
        path: ~/.gradle/caches # Caching multiple paths, to also include OSS Index cache, will be added on actions/cache@v2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: eskatos/gradle-command-action@v1
      name: ossIndexAudit
      with:
        arguments: ossIndexAudit --no-daemon --info
